### ISSUE TITLE
Status de pagamento. 

### ISSUE THREAD

**Issue by phzsantos** [terroo/terminal-finances#6]
Olá Marcos, 
eu estou usando o Finances para controlar as contas de casa e percebi que pode ser adicionada uma melhoria. 

Ela ficaria em: Inserir Créditos e/ou Débito, Editar e Excluir Lançamentos

A melhoria é a seguinte: Adicionar uma coluna Status depois de Operação;

Nessa coluna status teria duas opções: Pago ou Pendente.

Qual seria a função disso?

Quando você for na tela de Relatórios, você poderia adicionar mais um campo ao lado de Crédito, Saldo e Débito com o nome pendente.

Assim a pessoa vai poder ver quanto ela obteve de credito, quanto gastou, qual foi o saldo e quanto ainda está pendente de ser pago (que não entra na conta do saldo, credito e debito).

Att, phzsantos.

**Comment by terroo** [comment]
Boa dica, gostei! Adicionei ao novos recursos. No próximo patch vou tentar incluir. Obrigado pela contribuição!
