### ISSUE TITLE
bug in windows

### ISSUE THREAD

**Issue by KitsuneSemCalda** [terroo/terminal-finances#7]
Olá Marcos, tentei usar o terminal finances no windows e substituir o velho excel da microsoft, mas quando vou adicionar o debito ou o crédito dá uma falha e não adiciona, o que poderia ser? o programa tem alguma dependência necessária faltante?

**Comment by terroo** [comment]
Faça o download desse arquivo:

https://github.com/terroo/terminal-finances/blob/main/src/terminalfinances/terminalfinances.db

E cole dentro da pasta que você instalou substituindo o que há lá e tente de novo pra ver se deu certo.

**Comment by KitsuneSemCalda** [comment]
Já tentei mas ainda ocorre uma **"falha ao inserir dados"** 


![Captura de Tela (26)](https://user-images.githubusercontent.com/59454155/113483916-1ab72d80-947c-11eb-93ba-411e8293a11e.png)

**Comment by terroo** [comment]
Verifique se esse arquivo está com permissão de gravação ,clicando com o botão direito sobre ele e indo em propriedades.

**Comment by KitsuneSemCalda** [comment]
Resolveu o problema, agradecido
